"""posts table

Revision ID: 8a724ac6f117
Revises: c185d8a03ad6
Create Date: 2022-05-10 21:27:29.757758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a724ac6f117'
down_revision = 'c185d8a03ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('my_field', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'my_field')
    # ### end Alembic commands ###
