"""new fields in user model

Revision ID: 99e565c18f98
Revises: 8a724ac6f117
Create Date: 2022-05-16 21:20:17.127563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e565c18f98'
down_revision = '8a724ac6f117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'my_field')
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.add_column('post', sa.Column('my_field', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
